### ymlのインデントにおいて
### インデントについてかなり厳密
### 空白行やタブの使用でエラーが出る場合がある
### インデントのところでのエラーが履かれた場合は半角スペースを利用してみると解消される


#ワークフローの名前（任意）
name: front-github-actions

#mainブランチに対してPRが作成されたタイミングをトリガーとする
on:
  pull_request:
    branches:
      - main

#ワークフローで実行されるジョブをグループ化
jobs:
  #jobの名前を定義
  test:
    #最新バージョンのUbuntuLinuxランナーで実行するようにジョブを構成
    runs-on: ubuntu-latest
    #testジョブで実行されるステップをグループ化
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: install
        run: yarn install
      - name: ESLint
        run: yarn fix:eslint
      - name: Prettier
        run: yarn fix:prettier
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: public
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: public
          path: public
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
